# Shared Conventional Commits / Conventional Branch rules.
# Single source of truth for .githooks/*, .github/workflows/code-standards.yml, and the
# code-standards Claude Code skill (.claude/skills/code-standards/SKILL.md). Edit only here —
# everything else calls into the check-*.sh scripts that source this file.

# https://www.conventionalcommits.org/
COMMIT_TYPES="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"

# <type>(<scope>)!: <description> — scope and breaking-change "!" are optional.
COMMIT_MSG_REGEX="^(${COMMIT_TYPES})(\([a-z0-9./_-]+\))?!?: .{1,100}$"

# https://conventional-branch.github.io/ — mapped 1:1 to the commit types above so the same
# type vocabulary drives both commit messages and changelog generation.
BRANCH_TYPES="feature|bugfix|hotfix|release|chore|docs|refactor|test"
BRANCH_NAME_REGEX="^(${BRANCH_TYPES})/[a-z0-9._-]+$"

# Branches exempt from naming validation:
#   main/master/develop — trunk branches, never renamed to fit the scheme.
#   claude/*            — auto-generated by Claude Code worktree sessions, not user-named.
EXEMPT_BRANCH_REGEX="^(main|master|develop)$|^claude/"

is_merge_commit_msg() {
  grep -qE "^Merge (pull request|branch|remote-tracking branch) " "$1"
}
